// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PtF6FnX9LVzmlsuuBsLo3vF2H4qtb9Y',
    appId: '1:487296904576:web:088937abf5ac50411c2565',
    messagingSenderId: '487296904576',
    projectId: 'teja-com',
    authDomain: 'teja-com.firebaseapp.com',
    storageBucket: 'teja-com.appspot.com',
    measurementId: 'G-7HDLVQMZ5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGwrzlOrK51TUsc56p9HM4sbJNF-4nm0',
    appId: '1:487296904576:android:862b2a420b2f831a1c2565',
    messagingSenderId: '487296904576',
    projectId: 'teja-com',
    storageBucket: 'teja-com.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmqezacj15Mx-pE5o_shkXJ80MLVLB7QQ',
    appId: '1:487296904576:ios:56cc0e44f0430ae41c2565',
    messagingSenderId: '487296904576',
    projectId: 'teja-com',
    storageBucket: 'teja-com.appspot.com',
    iosBundleId: 'com.example.portfoliooo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmqezacj15Mx-pE5o_shkXJ80MLVLB7QQ',
    appId: '1:487296904576:ios:09d61be6ed2768761c2565',
    messagingSenderId: '487296904576',
    projectId: 'teja-com',
    storageBucket: 'teja-com.appspot.com',
    iosBundleId: 'com.example.portfoliooo.RunnerTests',
  );
}
